### ISSUE TITLE
How do you use <s>, </s>, <n> in your pretraining?

### ISSUE THREAD

**Issue by zixiliuUSC** [THUDM/Chinese-Transformer-XL#10]

**Comment by duzx16** [comment]
We didn't use <s> and </s>. The two tokens are added by sentencepiece automatically. The token for the end of text is <|endoftext|> (not added in sentencepiece but implemented in ChineseSPTokenizer). <n> is the token for "/n" since sentencepiece will consider "\n" as the end of sentences.
