### ISSUE TITLE
安装总是报错

### ISSUE THREAD

**Issue by DemonAlbert** [THUDM/Chinese-Transformer-XL#13]
![image](https://user-images.githubusercontent.com/50090212/203744442-479a6055-db03-4be1-9fa6-57fa50270c4a.png)
您好，我在安装这个的时候总是报错，请问如何解决，或者能不能像其他项目那样也做成一个完整的docker容器？

**Comment by duzx16** [comment]
可以使用GLM的镜像https://github.com/THUDM/GLM#docker-image
