### ISSUE TITLE
finetune模型报错

### ISSUE THREAD

**Issue by aph-asic** [THUDM/Chinese-Transformer-XL#17]
我已将模型进行切分，尝试使用单机两卡进行finetune，但是报如下错误：
DeepSpeed backend not set, please initialize it using init_process_group()

**Comment by duzx16** [comment]
这是因为代码不支持较高版本的DeepSpeed。可以使用DeepSpeed 0.5.9及以下的版本，也可以自己在代码中initialize_distributed中添加对deepspeed.init_process_group()的调用

**Comment by aph-asic** [comment]
> 好的好的，非常感谢
