### ISSUE TITLE
请问是否使用了sentencepiece的随机切分？

### ISSUE THREAD

**Issue by zixiliuUSC** [THUDM/Chinese-Transformer-XL#9]
发现您们的在使用sentencepiece的encode时，并没有像官网的例子那样采用sample=True，这样的话每次切分句子都是一样的没有变化的，所以是不是说你们没有像sentencepiece论文那样采用不用的切分增强模型鲁棒性呢？

**Comment by duzx16** [comment]
是的，我们没有使用随机切分。这个选项一般是在机器翻译中使用的，在预训练模型中不太常见
